name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  core:
    path: core
  movie:
    path: movie
  tv:
    path: tv
  about:
    path: about
  http: ^1.6.0

  dartz: ^0.10.1
  equatable: ^2.0.8
  google_fonts: ^8.0.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^9.2.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  firebase_core: ^4.7.0
  firebase_analytics: ^12.3.0
  firebase_crashlytics: ^5.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  mockito: ^5.6.4
  build_runner: ^2.13.1
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true