name: core
description: Core module for ditonton.

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  dartz: ^0.10.1
  equatable: ^2.0.8
  google_fonts: ^8.0.2
  cached_network_image: ^3.4.1
  get_it: ^9.2.1
  sqflite: ^2.4.2
  flutter_rating_bar: ^4.0.1
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5

dev_dependencies:
  mockito: ^5.6.4
  flutter_test:
    sdk: flutter
