name: Flutter CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install core dependencies
        run: cd core && flutter pub get
        
      - name: Install movie dependencies
        run: cd movie && flutter pub get
        
      - name: Install tv dependencies
        run: cd tv && flutter pub get

      - name: Run root tests
        run: flutter test

      - name: Run core tests
        run: cd core && flutter test
        
      - name: Run movie tests
        run: cd movie && flutter test

      - name: Run tv tests
        run: cd tv && flutter test
